name: mcp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - flask
  - flask-cors
  - requests
  - beautifulsoup4
  - pytest
  - pytest-cov
  - pytest-mock
  - numpy
  - sympy
  - pandas
  - matplotlib
  - pip:
    - wikipedia
    - duckduckgo-search
    - selenium
    - webdriver-manager
    - coverage
    - pytest-html
